language: cpp

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - zlib1g-dev

before_install:
  - wget -O cmocka.tar.xz https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
  - tar -xvf cmocka.tar.xz
  - cd cmocka-*
  - mkdir -p build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - make install
  - cd ../..
  - rm -rf cmocka*
  - wget -O zstd.tar.gz https://github.com/facebook/zstd/archive/v1.1.0.tar.gz
  - tar -xvf zstd.tar.gz
  - cd zstd*
  - make
  - make install PREFIX=$HOME/opt
  - cd ..
  - rm -rf zstd*
  - export LD_LIBRARY_PATH=$HOME/opt/lib
  - export C_PATH=$HOME/opt/include
  - export PKG_CONFIG_PATH=$HOME/opt/lib/pkgconfig


script:
  - make clean test all
  - make install PREFIX=$HOME/opt
