language: cpp

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - zlib1g-dev

before_install:
  - wget -O cmocka.tar.xz https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
  - tar -xvf cmocka.tar.xz
  - cd cmocka-*
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - sudo make install
  - cd ../..
  - rm -rf cmocka*


script:
  - make clean test all
  - sudo make install PREFIX=$PWD/target
